[alias]
dev = ["run", "-p", "xtask", "--", "dev"]
dev-watch = ["run", "-p", "xtask", "--", "dev-watch"]
run-app-macos = ["run", "-p", "xtask", "--", "run-app-macos"]
list-apps = ["run", "-p", "xtask", "--", "list-apps"]
resolve-package = ["run", "-p", "xtask", "--", "resolve-package"]
package-macos = ["run", "-p", "xtask", "--", "package-macos"]
package-dmg = ["run", "-p", "xtask", "--", "package-dmg"]
package-windows = ["run", "-p", "xtask", "--", "package-windows"]
sync-fonts = ["run", "-p", "xtask", "--", "sync-fonts"]
sync-icons = ["run", "-p", "xtask", "--", "sync-icons"]
